"""初始 Mock 資料——與前端 mockData.ts 同步"""
from app.models import Device, Alert, WorkOrder, KPIData, BimLocation
from datetime import datetime, timedelta


def _dt(minutes_ago: int) -> str:
    return (datetime.now() - timedelta(minutes=minutes_ago)).isoformat()


DEVICES: list[Device] = [
    Device(id='dev-001', asset_code='AHU-A-3F-01', name='A棟3F空調箱01',
           category='HVAC', asset_type='AHU', status='critical',
           current_power_kw=42.3, floor=3, building_id='bldg-a',
           position=[-18, 6, 0], bim_location=BimLocation(x=-18, y=6, z=0),
           manufacturer='Carrier', model='AHU-3000',
           install_date='2018-06-15', warranty_expiry='2023-06-15',
           rul_days=45, criticality='HIGH', temperature=28.5, ai_score=0.87),
    Device(id='dev-002', asset_code='CHW-A-B1-01', name='A棟B1冰水主機01',
           category='HVAC', asset_type='Chiller', status='normal',
           current_power_kw=185.0, floor=-1, building_id='bldg-a',
           position=[-18, -1, 0], bim_location=BimLocation(x=-18, y=-1, z=0),
           manufacturer='Trane', model='RTHD-200',
           install_date='2018-01-01', warranty_expiry='2025-01-01',
           rul_days=420, criticality='CRITICAL', temperature=6.2, ai_score=0.12),
    Device(id='dev-003', asset_code='METER-A-B1-M', name='A棟主電表',
           category='Power', asset_type='Meter', status='normal',
           current_power_kw=320.5, floor=-1, building_id='bldg-a',
           position=[-20, -1, 2], bim_location=BimLocation(x=-20, y=-1, z=2),
           manufacturer='Schneider', model='PM8000',
           install_date='2018-01-01', warranty_expiry='2028-01-01',
           rul_days=1200, criticality='CRITICAL', ai_score=0.05),
    Device(id='dev-004', asset_code='UPS-A-2F-01', name='A棟2F UPS-01',
           category='Power', asset_type='UPS', status='warning',
           current_power_kw=12.0, floor=2, building_id='bldg-a',
           position=[-18, 4, -2], bim_location=BimLocation(x=-18, y=4, z=-2),
           manufacturer='Eaton', model='9PX-10K',
           install_date='2020-03-15', warranty_expiry='2025-03-15',
           rul_days=180, criticality='HIGH', temperature=38.1, ai_score=0.65),
    Device(id='dev-005', asset_code='AHU-A-6F-01', name='A棟6F空調箱01',
           category='HVAC', asset_type='AHU', status='normal',
           current_power_kw=38.7, floor=6, building_id='bldg-a',
           position=[-18, 12, 0], bim_location=BimLocation(x=-18, y=12, z=0),
           manufacturer='Carrier', model='AHU-3000',
           install_date='2018-06-15', warranty_expiry='2023-06-15',
           rul_days=620, criticality='MEDIUM', temperature=24.3, ai_score=0.08),
    Device(id='dev-006', asset_code='AHU-B-2F-01', name='B棟2F精密空調',
           category='HVAC', asset_type='CRAC', status='normal',
           current_power_kw=55.0, floor=2, building_id='bldg-b',
           position=[0, 4, 0], bim_location=BimLocation(x=0, y=4, z=0),
           manufacturer='Stulz', model='CyberAir-30',
           install_date='2021-02-01', warranty_expiry='2026-02-01',
           rul_days=850, criticality='HIGH', temperature=22.0, ai_score=0.04),
    Device(id='dev-007', asset_code='METER-B-M', name='B棟主電表',
           category='Power', asset_type='Meter', status='normal',
           current_power_kw=210.3, floor=1, building_id='bldg-b',
           position=[2, 2, 3], bim_location=BimLocation(x=2, y=2, z=3),
           manufacturer='ABB', model='A44',
           install_date='2021-01-01', warranty_expiry='2031-01-01',
           rul_days=1800, criticality='CRITICAL', ai_score=0.03),
    Device(id='dev-008', asset_code='PV-B-R', name='B棟屋頂PV系統',
           category='Power', asset_type='PV', status='normal',
           current_power_kw=-45.2, floor=6, building_id='bldg-b',
           position=[0, 15, 0], bim_location=BimLocation(x=0, y=15, z=0),
           manufacturer='SMA', model='Tripower-50',
           install_date='2022-05-01', warranty_expiry='2032-05-01',
           rul_days=2000, criticality='LOW', ai_score=0.02),
    Device(id='dev-009', asset_code='RACK-C-1F-A01', name='C棟機架A01',
           category='IT', asset_type='Rack', status='warning',
           current_power_kw=8.5, floor=1, building_id='bldg-c',
           position=[20, 2, -2], bim_location=BimLocation(x=20, y=2, z=-2),
           manufacturer='APC', model='NetShelter-42U',
           install_date='2022-01-01', warranty_expiry='2027-01-01',
           rul_days=300, criticality='HIGH', temperature=35.8, ai_score=0.58),
    Device(id='dev-010', asset_code='CRAC-C-1F-01', name='C棟1F精密空調',
           category='HVAC', asset_type='CRAC', status='offline',
           current_power_kw=0, floor=1, building_id='bldg-c',
           position=[20, 2, 2], bim_location=BimLocation(x=20, y=2, z=2),
           manufacturer='Liebert', model='Challenger-75',
           install_date='2022-01-01', warranty_expiry='2027-01-01',
           rul_days=0, criticality='CRITICAL', temperature=42.1, ai_score=0.95),
    Device(id='dev-011', asset_code='UPS-C-1F-01', name='C棟機房UPS-01',
           category='Power', asset_type='UPS', status='normal',
           current_power_kw=35.0, floor=1, building_id='bldg-c',
           position=[22, 2, 0], bim_location=BimLocation(x=22, y=2, z=0),
           manufacturer='Eaton', model='9395-160',
           install_date='2022-01-01', warranty_expiry='2027-01-01',
           rul_days=720, criticality='CRITICAL', ai_score=0.06),
]

ALERTS: list[Alert] = [
    Alert(id='al-001', asset_id='dev-001', asset_name='A棟3F空調箱01',
          title='AHU-A-3F-01 高壓保護跳脫',
          description='冷媒壓力異常，高壓開關跳脫停機',
          severity='CRITICAL', status='open', occurred_at=_dt(5),
          ai_root_cause='冷媒充填量不足，研判為冷媒洩漏或膨脹閥故障',
          ai_action_suggestion='立即停機，補充冷媒，派遣冷凍空調技術士',
          floor=3, building_id='bldg-a'),
    Alert(id='al-002', asset_id='dev-010', asset_name='C棟1F精密空調',
          title='CRAC-C-1F-01 通訊中斷離線',
          description='設備通訊中斷超過 15 分鐘，機房溫度 42.1°C',
          severity='CRITICAL', status='open', occurred_at=_dt(18),
          ai_root_cause='精密空調離線，機房散熱能力喪失',
          floor=1, building_id='bldg-c'),
    Alert(id='al-003', asset_id='dev-004', asset_name='A棟2F UPS-01',
          title='UPS-A-2F-01 電池溫度偏高',
          description='電池組溫度 38.1°C，超過建議上限 35°C',
          severity='WARNING', status='acknowledged', occurred_at=_dt(45),
          floor=2, building_id='bldg-a'),
]

WORK_ORDERS: list[WorkOrder] = [
    WorkOrder(id='wo-001', wo_number='WO-2026-001234', wo_type='EM',
              title='AHU-A-3F-01 高壓保護跳脫緊急維修',
              priority='URGENT', status='in_progress',
              asset_id='dev-001', asset_name='A棟3F空調箱01',
              assigned_to='陳大維', estimated_hours=3.0,
              created_at=_dt(4), ai_root_cause='冷媒洩漏或膨脹閥故障'),
    WorkOrder(id='wo-002', wo_number='WO-2026-001235', wo_type='EM',
              title='CRAC-C-1F-01 通訊中斷緊急排查',
              priority='URGENT', status='pending',
              asset_id='dev-010', asset_name='C棟1F精密空調',
              assigned_to='林志明', estimated_hours=1.5,
              created_at=_dt(17)),
    WorkOrder(id='wo-003', wo_number='WO-2026-001230', wo_type='PM',
              title='B棟季度空調保養',
              priority='MEDIUM', status='in_progress',
              asset_id='dev-006', asset_name='B棟2F精密空調',
              assigned_to='王建國', estimated_hours=4.0,
              created_at=_dt(120)),
]

KPI = KPIData(
    total_devices=11, online_devices=8, warning_devices=2,
    critical_devices=2, offline_devices=1,
    total_power_kw=668.3, demand_kw=875.0, contract_demand_kw=1000.0,
    demand_ratio_pct=87.5, today_kwh=8254.0,
    open_alerts=2, pending_work_orders=1, in_progress_work_orders=2,
    today_completed_work_orders=3, mttr_hours=2.3, mtbf_days=142.0,
    availability_pct=98.6,
)
